name: lint-and-test-fast

on:
  push:
    branches: [ develop, feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install TA-Lib (precompiled wheel - faster)
        run: |
          python -m pip install --upgrade pip
          pip install TA-Lib --prefer-binary
          
      - name: Install freqtrade
        run: |
          pip install freqtrade
          
      - name: Validate strategies
        run: |
          freqtrade list-strategies --userdir user_data